spring:
  application:
    name: "http-service1"

server:
  port: 8080

httpservice2:
  endpoint: "http://localhost:8081"

management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      produce: W3C # B3C
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  otlp:
    # tracing:
    #   endpoint: http://localhost:4318/v1/traces
    metrics:
      export:
        enabled: false
  endpoints:
    web:
      exposure:
        # include: health,info,prometheus
        include: "*"