apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: httpservice1
  name: httpservice1
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: httpservice1
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (HEAD)
        kuma.io/envoy-log-level: "debug"
      labels:
        io.kompose.service: httpservice1
    spec:
      containers:
        - env:
            - name: HTTPSERVICE2_ENDPOINT
              value: http://httpservice2.demo.svc:8081
            - name: MANAGEMENT_OTLP_TRACING_ENDPOINT
              value: http://172.18.1.3:4318/v1/traces
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: http://172.18.1.3:9411/api/v2/spans
          image: pileenretard/httpservice1-micrometer:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          name: httpservice1
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
