apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: httpservice2
  name: httpservice2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: httpservice2
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (HEAD)
        kuma.io/envoy-log-level: "debug"
      labels:
        io.kompose.service: httpservice2
    spec:
      containers:
        - env:
            - name: MANAGEMENT_OTLP_TRACING_ENDPOINT
              value: http://172.18.1.3:4318/v1/traces
            - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
              value: http://172.18.1.3:9411/api/v2/spans
          image: pileenretard/httpservice2-micrometer:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          name: httpservice2
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
