apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: httpservice2
  name: httpservice2
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
      appProtocol: http
  selector:
    io.kompose.service: httpservice2
